services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: changemeinprod!
    ports:
      - "5432:5432"
    restart: always

  adminer:
    image: adminer:latest
    ports:
      - "8888:8080"
    restart: always